 insert into books (id, title, author, subject, first_publish_year, description) 
 values
  ('OL26501179M','Pride and Prejudice','Jane Austen', 'Romance, Ladies, Fiction, love stories, marriage, wealth, class, manners, Englisch, Roman, Pride and prejudice (Austen, Jane), Sisters, Young women, Courtship, Social classes, Fiction, Social life and customs, Mate selection, Sociala klasser i litteraturen, Gentry, Manners and customs, Prophecies, Bible, History of Biblical events, Families, Great Britain, Reading Level-Grade 7', '1813', 'Pride and Prejudice is a Jane Austen classic comic romance, in which the five Bennett sisters try to find that most elusive creature: a single man in possession of a large fortune. Sparks fly when sweet, pretty Jane meets their new neighbor, Mr. Bingley, but her sister Elizabeth is most offended by his haughty friend, Mr. Darcy. This is Austen at the height of her powers: the ironic narration, hilariously drawn supporting characters, and romantic suspense make this her most enduringly popular novel.'),
  ('OL27071765M','The Lord of the Rings','J.R.R. Tolkien','Fiction, Fantasy, Adventure, English', '1950','In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring to rule all the others. But the One Ring was taken from him, and remained lost until after many ages it fell by chance into the hands of the hobbit, Bilbo, and was then bequeathed to his young nephew Frodo. The Lord of the Rings tells of the quest undertaken by Frodo together with the fellowship of the ring: Gandalf the wizard, Merry, Pippin, and Sam the hobbits, Gimli the dwarf, Legolas the elf, Boromir mand of Gondor, and a tall mysterious stranger called Strider.'),
  ('OL6492763M','Jane Eyre', 'Charlotte Brontë', 'Relationships, Women, Fiction', '1847','The novel is set somewhere in the north of England. Janes childhood at Gateshead Hall, where she is emotionally and physically abused by her aunt and cousins; her education at Lowood School, where she acquires friends and role models but also suffers privations and oppression; her time as the governess of Thornfield Hall, where she falls in love with her Byronic employer, Edward Rochester; her time with the Rivers family, during which her earnest but cold clergyman cousin, St John Rivers, proposes to her. Will she or will she not marry him?'),
  ('OL28212280M','To Kill a Mockingbird', 'Harper Lee', ' Fiction, Classics, Segregation, mob mentality, Southern Gothic, southern life, racial injustice, class, courage, compassion, gender roles, laws, loss of innocence, rape trials, domestic fiction, legal stories, Bildungsromans, Race relations, Lawyers, Girls, Prejudices, Fathers and daughters, Trials (Rape), Great Depression, African Americans, Father-', '1960','Shoot all the Bluejays you want, if you can hit em, but remember its a sin to kill a Mockingbird. A lawyers advice to his children as he defends the real mockingbird of Harper Lees classic novel - a black man charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the thirties. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one mans struggle for justice. But the weight of history will only tolerate so much.'),
  ('OL16165161M','The Kite Runner', 'Khaled Hosseini', 'Betrayal, Fiction, Boys, New York Times bestseller, Soviet-Afghan war, Mullahs, sadistic personality disorder, brass knuckles, fighter kites, Pashtuns, Hazaras, literary fiction, Teenage boys, Bildungsromans, Competitions, Kites, Literature,', '2003','Twelve-year-old Amir is desperate to gain the approval of his father and resolves to win the local kite-fighting tournament, to prove that he has the makings of a man. His loyal friend Hassan promises to help him - for he always helps Amir - but this is 1970s Afghanistan and Hassan is merely a low-caste servant who is jeered at in the street, although Amir feels jealous of his natural courage and the place he holds in his fathers heart. But neither of the boys could foresee what would happen to Hassan on the afternoon of the tournament, which was to shatter their lives. After the Russians invade and the family is forced to flee to America, Amir realises that one day he must return to find the one thing that his new wold cannot grant him: redemption.'),
  ('OL26615999M','Gone with the Wind', 'Margaret Mitchell','Survival, Slavery, History, historical fiction, war stories, United States Civil War, Women, Open Library Staff Picks, Fiction in English, Pulitzer Prize Winner, Fiction, Historia, Novela, award:pulitzer_prize=fiction, award:pulitzer_prize=1937, Plantation life', '1936',''),
  ('OL18290341M', 'The Catcher in the Rye', 'J. D. Salinger', 'Classics, Young Adult, Fiction, Literature, Study and teaching, Young adult literature, Fiction, coming of age, American fiction (fictional works by one author), Caulfield, holden (fictitious character), fiction, New york (n.y.), fiction', '2012',''),
  ('OL26499577M', 'Wuthering Heights', 'Emily Brontë',' Classics, Fiction, Drama, Historical Fiction, romance, love, death, Rejection (Psychology), Triangles (Interpersonal relations), Rural families, Man-woman relationships, fiction in English, England in fiction, Orphans in fiction, foundlings in fiction, revenge, Man-woman relationships in fiction, Open Library Staff Picks, Landscape in literature in fiction, Country life in fiction, Landscape','1847',''),

  ('OL28419977M', 'The Hunger Games', 'Suzzane Collins', 'Action, Dystopian, Romance, starvation, oppression, effects of war, self-sacrifice, Science fiction, Apocalyptic fiction, Dystopian fiction, Fiction, Juvenile works, Novels, Young adult works, Juvenile fiction, contensts, Young adult fiction, Game shows, Television programs, New York Times bestseller, Contests, nyt:series_books=2010-08-21, Long Now Manual for Civilization, Reality television','2008','COULD YOU SURVIVE ON YOUR OWN, IN THE WILD, WITH EVERYONE OUT TO MAKE SURE YOU DONT LIVE TO SEE THE MORNING? In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.'),
  ('OL2769393M', 'The Handmaids Tale', 'Margaret Atwood', 'Misogyny, Fiction, Women, Dystopias, brothels, Scrabble, Christian fundamentalism, revolution, military dictatorship, Old Testament, religious fanaticism, totalitarianism, theonomy, handmaids, United States Congress, fantasy fiction, Canadian fantasy fiction, Dystopian fiction, Canadian authors, theocracy, pregnancy, political fiction, science fiction, Canadian fiction', '1985',''),
  ('OL26790972M', 'Divergent', 'Veronica Roth', ' Young Adult, Fiction, Dystopian, sci-fi, science fiction, YA, dystopian YA, bestseller, future, Families, Juvenile fiction, Family life, Social classes, Courage, Identity, Identity (Philosophical concept), Identity (Psychology), YOUNG ADULT FICTION, Romance, Individuality,', '2011',''),
  ('OL28166116M', 'The Testaments', 'Margaret Atwood', 'Science Fiction, Young Adult, Dystopian, Fiction, dystopian, Fiction, fantasy, general, Canadian fiction (fictional works by one author)', '1999',''),
  ('OL7996404M', 'Among the Imposters', 'Margaret Peterson Haddix', 'Science Fiction, Young Adult, Fiction, Dystopian Fiction', '2002',''),

  ('OL27579080M', 'Steve Jobs', 'Walter Isaacson','Biography, Technology, Modern', '2019',''),
  ('OL28270888M', 'The Diary of a Young Girl', 'Anne Frank','Biography, Holocaust, War', '1947',''),
  ('OL10686970M', 'A Long Walk to Freedom', 'Nelson Mandela', ' Biography, Politics, Presidents, African National Congress, Civil rights workers, Political prisoners, Statesmen, Human rights, Mandela, Nelson, 1918-, Apartheid, Guerilla Warfare, Reading Level-Grade 11, Reading Level-Grade 12, Anti-apartheid movement, Autobiografie, South africa, politics and government, South africa, history, Mandela, nelson,', '1994',''),
  ('OL343856M', 'A Beautiful Mind', 'Sylvia Nasar', 'Math, Biography, Genius, Mathematicians, Nobelprijzen, Economen, Schizophrenia, Wiskundigen, Mathematics, Speltheorie, Biography, Schizophrenics, biography, Mathematicians, biography, Large type books','2001',''),
  ('OL28541494M','Alan Turing : the Enigma', 'Andrew Hodges', 'Biography, Mathematics, War, 1912-1954, Mathematicians, biography, Mathematicians, HISTORY / Europe / Germany, Biography','1983',''),
  ('OL24333327M', 'Alexander Hamilton', 'Ron Chernow', 'Politics, Government, Biography, Statesmen, Biography & Autobiography, History, Nonfiction, Government, Hamilton, alexander, 1757-1804, Statesmen, biography, Statesmen, united states, United states, politics and government, 1783-1809','2004',''),

  ('OL7573027M', 'The Godfather', 'Mario Puzo', 'Movies, Crime, Italian, Detective and mystery stories, Organized crime, Criminals, Italian Americans, Mafia, Fiction, Criminals in fiction, Drama, Fiction in English, Italian Americans in fiction, Mafia in fiction, Organized crime in fiction, Romance, Corleone family (Fictitious characters), English fiction, Crime, fiction, Criminals, fiction, Italian americans, fiction, New york (n.y.), fiction, Fiction, mystery & detective, general, Large type books','1969', 'Thirty years ago, an American classic was born. With it brilliant and brutal portrayal of the Corleone family, The Godfather burned its way into our national consciousness-and became one of the bestselling books in publishing history. Now, this unforgettable saga of crime and corruption, passion and loyalty continues to stand the test of time, as the definitive novel of the Mafia underworld.'),
  ('OL7454243M','Fight Club','Chuck Palahniuk','Movie, Fiction, Young Men, Millennialism, Young men, Science fiction, open_syllabus_project, Hand-to-hand fighting, Gangs, Self-destructive behavior, Boxing, Aggressiveness, Fiction, general, United states, fiction, Fiction, media tie-in, Fiction, science fiction, action & adventure','1999','A man who struggles with insomnia meets a colorful extremist, and they create a secret organization together. Chuck Palahniuk showed himself to be his generation’s most visionary satirist in this, his first book. Fight Club’s estranged narrator leaves his lackluster job when he comes under the thrall of Tyler Durden, an enigmatic young man who holds secret after-hours boxing matches in the basement of bars. There, two men fight "as long as they have to." This is a gloriously original work that exposes the darkness at the core of our modern world.'),
  ('OL8870184M','Little Women','Louisa May Alcott','Movie, Classic, American, Juvenile, American, Children, Literature, History, Historical, Fiction, March family (Fictitious characters), Family, Families, Family life, Sisters, Young women, Mothers, Daughtes, Married women, Orphans, Coming of life, Manners, Customs, Conduct of life, Social life','1868','A story of four young women and their varied adventures This classic story of the March family women and their lives in New England during the Civil War has remained enduringly popular since its publication in 1868. Poor, argumentative, loving, and optimistic, the March sisters struggle to supplement their familys meager income and realize their own dreams. This highly autobiographical novel shows us women who are strong-minded and independent in their determination to control their own destiny. The introduction to this edition provides a fascinating history of the Alcotts, and a biographical history of Louisa Alcotts own struggles as a writer. '),
  ('OL7511248M','The Wizard of Oz','L. Frank Baum','Movie, Witches, Fantasy, Toy and movable books, Spanish language materials, Fiction, Wizards, Juvenile literature, Wizards in fiction, Russian, Specimens, Imaginary voyages in fiction, Classic Literature, Imaginary Voyages, American, Adventure and adventurers, Open Library Staff Picks, Books and reading,  Witches in fiction, History, Juvenile fiction', '2019',''),
  ('OL7950355M','Forrest Gump','Winston Groom','Movie,  Young Men, War, People with mental disabilities, Fiction, WWII, war, veterans, Forrest Gump','1986',''),
  ('OL28346251M','The Princess Bride','William Goldman','Movie, Adventure, Fiction','1973',''),

  ('OL22856696M', 'Harry Potter And The Philosophers Stone', 'J. K. Rowling', ' Ghosts, Monsters, Vampires, Witches, Challenges and Overcoming Obstacles, Magic and Supernatural, Cleverness, School Life, school stories, Wizards, Magic, MAGIA, MAGOS, Juvenile fiction, Fiction, NOVELAS INGLESAS, Schools, orphans, fantasy fiction, England in fiction, Witches in fiction, Wizards in fiction, Alchemy, New York Times bestseller, Juvenile literature, Magic in fiction, Open Library Staff Picks, Juvenile audience','1997','Harry Potters life is miserable. His parents are dead and he is stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he is a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.'),
  ('OL10682512M', 'The Hobbit Or There And Back Again', 'J.R.R. Tolkien', 'hobbits, wizards, dragons, dwarves, elves, men, trolls, goblins, giant spiders, the one ring, juvenile fantasy, YOUNG ADULT FICTION, Fantasy fiction, Juvenile fiction, Fiction, Fantasy, Classics, General', '1937', '')
;