 insert into books (id, title, author, subject, first_publish_year) 
 values
  ('OL26501179M','Pride and Prejudice','Jane Austen', 'feelings, young ladies, domestic fiction, love stories, marriage, wealth, class, manners, Englisch, Roman, Pride and prejudice (Austen, Jane), Sisters, Young women, Courtship, Social classes, Fiction, Social life and customs, Mate selection, Sociala klasser i litteraturen, Gentry, Manners and customs, Prophecies, Bible, History of Biblical events, Families, Great Britain, Reading Level-Grade 7', '1813'),
  ('OL27071765M','The Lord of the Rings','J.R.R. Tolkien',' The Lord of the Rings, Fiction, Ficción, English Fantasy fiction, Ficción fantástica inglesa, Fantasy fiction, Fiction in English, Open Library Staff Picks, Middle Earth (Imaginary place), Fiction, fantasy, epic, Middle earth (imaginary place), fiction, Baggins, frodo (fictitious character), fiction, Gandalf (fictitious character), fiction, British and irish fiction (fictional works by one author), English', '1950'),
  ('OL6492763M', 'Jane Eyre', 'Charlotte Brontë',' Man-woman relationships, Carnegie Endowment for International Peace, Charity-schools, Married people in fiction, American Jewish Congress, Country homes, Country homes in fiction, Fathers and daughters in fiction, Faculty, Open Library Staff Picks, Orphans in fiction, Young women, Married men in fiction, New York times, Correspondence, Mentally ill women, Vietnam War, 1961-1975,', '1847'),
  ('OL28212280M', 'To Kill a Mockingbird', 'Harper Lee', ' fiction, fiction classics, contemporary fiction, racial segregation, mob mentality, Southern Gothic, southern life, racial injustice, class, courage, compassion, gender roles, laws, loss of innocence, rape trials, domestic fiction, legal stories, Bildungsromans, Race relations, Lawyers, Girls, Prejudices, Fathers and daughters, Trials (Rape), Great Depression, African Americans, Father-', '1960'),
  ('OL16165161M','The Kite Runner', 'Khaled Hosseini', ' Male friendship, Betrayal, Fiction, Social classes, Boys, New York Times bestseller, nyt:trade_fiction_paperback=2009-09-26, Bacha bazi, Soviet-Afghan war, Mullahs, sadistic personality disorder, brass knuckles, fighter kites, Pashtuns, Hazaras, literary fiction, Teenage boys, Bildungsromans, Competitions, Kites, Literature,', '2003'),
  ('OL26615999M','Gone with the Wind', 'Margaret Mitchell',' survival, slavery, Bildungsroman, open_syllabus_project, history, historical fiction, war stories, United States Civil War, Women, Open Library Staff Picks, Fiction in English, Pulitzer Prize Winner, Fiction, Historia, Novela, award:pulitzer_prize=fiction, award:pulitzer_prize=1937, Plantation life', '1936'),
  ('OL18290341M', 'The Catcher in the Rye', 'J. D. Salinger', ' Study and teaching (Secondary), Literature, Study and teaching, Young adult literature, Fiction, coming of age, American fiction (fictional works by one author), Caulfield, holden (fictitious character), fiction, New york (n.y.), fiction', '2012'),
  ('OL26499577M', 'Wuthering Heights', 'Emily Brontë',' Classic Literature, Fiction, Drama, Historical Fiction, romance, love, death, Rejection (Psychology), Triangles (Interpersonal relations), Rural families, Man-woman relationships, fiction in English, England in fiction, Orphans in fiction, foundlings in fiction, revenge, Man-woman relationships in fiction, Open Library Staff Picks, Landscape in literature in fiction, Country life in fiction, Landscape','1847'),

  ('OL28419977M', 'The Hunger Games', 'Suzzane Collins', 'severe poverty, starvation, oppression, effects of war, self-sacrifice, Science fiction, Apocalyptic fiction, Dystopian fiction, Fiction, Juvenile works, Novels, Young adult works, Juvenile fiction, contensts, Young adult fiction, Game shows, Television programs, New York Times bestseller, Contests, nyt:series_books=2010-08-21, Long Now Manual for Civilization, Reality television','2008'),
  ('OL2769393M', 'The Handmaids Tale', 'Margaret Atwood', 'Man-woman relationships, Misogyny, Fiction, Women, Dystopias, brothels, Scrabble, Christian fundamentalism, revolution, military dictatorship, Old Testament, religious fanaticism, totalitarianism, theonomy, handmaids, United States Congress, fantasy fiction, Canadian fantasy fiction, Dystopian fiction, Canadian authors, theocracy, pregnancy, political fiction, science fiction, Canadian fiction', '1985'),
  ('OL26790972M', 'Divergent', 'Veronica Roth', ' dystopian, young adult, fiction, dystopian fiction, sci-fi, science fiction, YA, dystopian YA, bestseller, future, Families, Juvenile fiction, Family life, Social classes, Courage, Identity, Identity (Philosophical concept), Identity (Psychology), YOUNG ADULT FICTION, Romance, Individuality,', '2011'),
  ('OL28166116M', 'The Testaments', 'Margaret Atwood', 'Science Fiction, Young adult fiction, Dystopian Fiction, Fiction, dystopian, Fiction, fantasy, general, Canadian fiction (fictional works by one author)', '1999'),
  ('OL7996404M', 'Among the Imposters', 'Margaret Peterson Haddix', 'Science Fiction, Young adult fiction, Dystopian Fiction', '2002'),

  ('OL27579080M', 'Steve Jobs', 'Walter Isaacson','biography', '2019'),
  ('OL28270888M', 'The Diary of a Young Girl', 'Anne Frank','biography', '2019'),
  ('OL10686970M', 'A Long Walk to Freedom', 'Nelson Mandela', ' Biography, Politics and government, Presidents, African National Congress, Civil rights workers, Political prisoners, Statesmen, Human rights, Mandela, Nelson, 1918-, Apartheid, Guerilla Warfare, Reading Level-Grade 11, Reading Level-Grade 12, Anti-apartheid movement, Autobiografie, South africa, politics and government, South africa, history, Mandela, nelson,', '2019'),
  ('OL343856M', 'A Beautiful Mind', 'Sylvia Nasar', 'Schizophrenics, Schizofrenie, Mathématiciens, Mentally ill, Biographies, Mathematicians, Nobelprijzen, Economen, Schizophrenia, Wiskundigen, Mathematics, Speltheorie, Biography, Schizophrenics, biography, Mathematicians, biography, Large type books','2019'),
  ('OL28541494M','Alan Turing : the Enigma', 'Andrew Hodges', 'Turing, alan mathison, 1912-1954, Mathematicians, biography, Mathematicians, HISTORY / Europe / Germany, Biography','2019'),
  ('OL24333327M', 'Alexander Hamilton', 'Ron Chernow', 'Politics and government, Biography, Statesmen, Biography & Autobiography, History, Nonfiction, Government, Hamilton, alexander, 1757-1804, Statesmen, biography, Statesmen, united states, United states, politics and government, 1783-1809','2019'),

  ('OL7573027M', 'The Godfather', 'Mario Puzo', 'movies,  Detective and mystery stories, Organized crime, Criminals, Italian Americans, Mafia, Fiction, Criminals in fiction, Drama, Fiction in English, Italian Americans in fiction, Mafia in fiction, Organized crime in fiction, Romance, Corleone family (Fictitious characters), English fiction, Crime, fiction, Criminals, fiction, Italian americans, fiction, New york (n.y.), fiction, Fiction, mystery & detective, general, Large type books','2019'),
  ('OL7454243M','Fight Club','Chuck Palahniuk','movie,  Fiction, Millennialism, Young men, Science fiction, open_syllabus_project, Hand-to-hand fighting, Gangs, Self-destructive behavior, Boxing, Aggressiveness, Fiction, general, United states, fiction, Fiction, media tie-in, Fiction, science fiction, action & adventure','2019'),
  ('OL8870184M','Little Women','Louisa May Alcott','movie,  Children, Kids, Juvenile, American, Classic, Literature, History, Historical, Fiction, March family (Fictitious characters), Family, Families, Family life, Sisters, Young women, Mothers, Daughtes, Married women, Orphans, Coming of life, Manners, Customs, Conduct of life, Social life','2019'),
  ('OL7511248M','The Wizard of Oz','L. Frank Baum','movie, Witches, Toy and movable books, Spanish language materials, Fiction, Wizards, Juvenile literature, Wizards in fiction, Russian, Specimens, Imaginary voyages in fiction, Classic Literature, Imaginary Voyages, American, Adventure and adventurers, Open Library Staff Picks, Books and reading,  Witches in fiction, History, Juvenile fiction', '2019'),
  ('OL7950355M','Forrest Gump','Winston Groom','movie,  Young men, People with mental disabilities, Fiction, WWII, war, veterans, Forrest Gump','2019'),
  ('OL28346251M','The Princess Bride','William Goldman','movie','2019')
