 insert into books (id, title, author, subject) 
 values
  ('OL7353617M', 'Fantastic Mr. Fox','Roald Dahl', 'adventure, children'),
  ('OL365902M', 'We Shall Not Sleep','Anne Perry', 'historical, fiction'),
  ('OL24222441M', 'The Hunger Games', 'Suzanne Collins', 'adventure, women in literature'),
  ('OL26455544M', 'Catching Fire (The Hunger Games #2)', 'Suzanne Collins', 'sequel, adventure'),

  ('OL9039929W', 'Pride and Prejudice','Jane Austen', 'feelings, young ladies, domestic fiction, love stories, marriage, wealth, class, manners, Englisch, Roman, Pride and prejudice (Austen, Jane), Sisters, Young women, Courtship, Social classes, Fiction, Social life and customs, Mate selection, Sociala klasser i litteraturen, Gentry, Manners and customs, Prophecies, Bible, History of Biblical events, Families, Great Britain, Reading Level-Grade 7'),
  ('OL16165161M','The Kite Runner', 'Khaled Hosseini', ' Male friendship, Betrayal, Fiction, Social classes, Boys, New York Times bestseller, nyt:trade_fiction_paperback=2009-09-26, Bacha bazi, Soviet-Afghan war, Mullahs, sadistic personality disorder, brass knuckles, fighter kites, Pashtuns, Hazaras, literary fiction, Teenage boys, Bildungsromans, Competitions, Kites, Literature,'),
  ('OL267933W','Gone with the Wind', 'Margaret Mitchell',' survival, slavery, Bildungsroman, open_syllabus_project, history, historical fiction, war stories, United States Civil War, Women, Open Library Staff Picks, Fiction in English, Pulitzer Prize Winner, Fiction, Historia, Novela, award:pulitzer_prize=fiction, award:pulitzer_prize=1937, Plantation life'),
  ('OL20670575W', 'The Catcher in the Rye', 'J. D. Salinger', ' Study and teaching (Secondary), Literature, Study and teaching, Young adult literature, Fiction, coming of age, American fiction (fictional works by one author), Caulfield, holden (fictitious character), fiction, New york (n.y.), fiction'),
  ('OL27448W','The Lord of the Rings','J.R.R. Tolkien',' The Lord of the Rings, Fiction, Ficción, English Fantasy fiction, Ficción fantástica inglesa, Fantasy fiction, Fiction in English, Open Library Staff Picks, Middle Earth (Imaginary place), Fiction, fantasy, epic, Middle earth (imaginary place), fiction, Baggins, frodo (fictitious character), fiction, Gandalf (fictitious character), fiction, British and irish fiction (fictional works by one author), English'),
  ('OL6492763M', 'Jane Eyre', 'Charlotte Brontë',' Man-woman relationships, Carnegie Endowment for International Peace, Charity-schools, Married people in fiction, American Jewish Congress, Country homes, Country homes in fiction, Fathers and daughters in fiction, Faculty, Open Library Staff Picks, Orphans in fiction, Young women, Married men in fiction, New York times, Correspondence, Mentally ill women, Vietnam War, 1961-1975,'),
  ('OL3140834W', 'To Kill a Mockingbird', 'Harper Lee', ' fiction, fiction classics, contemporary fiction, racial segregation, mob mentality, Southern Gothic, southern life, racial injustice, class, courage, compassion, gender roles, laws, loss of innocence, rape trials, domestic fiction, legal stories, Bildungsromans, Race relations, Lawyers, Girls, Prejudices, Fathers and daughters, Trials (Rape), Great Depression, African Americans, Father-'),
  ('OL15035771W', 'Wuthering Heights', 'Emily Brontë',' Classic Literature, Fiction, Drama, Historical Fiction, romance, love, death, Rejection (Psychology), Triangles (Interpersonal relations), Rural families, Man-woman relationships, fiction in English, England in fiction, Orphans in fiction, foundlings in fiction, revenge, Man-woman relationships in fiction, Open Library Staff Picks, Landscape in literature in fiction, Country life in fiction, Landscape'),

  ('OL5735363W', 'The Hunger Games', 'Suzzane Collins', 'severe poverty, starvation, oppression, effects of war, self-sacrifice, Science fiction, Apocalyptic fiction, Dystopian fiction, Fiction, Juvenile works, Novels, Young adult works, Juvenile fiction, contensts, Young adult fiction, Game shows, Television programs, New York Times bestseller, Contests, nyt:series_books=2010-08-21, Long Now Manual for Civilization, Reality television'),
  ('OL15396204W', 'The Handmaids Tale', 'Margaret Atwood', 'Man-woman relationships, Misogyny, Fiction, Women, Dystopias, brothels, Scrabble, Christian fundamentalism, revolution, military dictatorship, Old Testament, religious fanaticism, totalitarianism, theonomy, handmaids, United States Congress, fantasy fiction, Canadian fantasy fiction, Dystopian fiction, Canadian authors, theocracy, pregnancy, political fiction, science fiction, Canadian fiction'),
  ('OL16813032W', 'Divergent', 'Veronica Roth', ' dystopian, young adult, fiction, dystopian fiction, sci-fi, science fiction, YA, dystopian YA, bestseller, future, Families, Juvenile fiction, Family life, Social classes, Courage, Identity, Identity (Philosophical concept), Identity (Psychology), YOUNG ADULT FICTION, Romance, Individuality,'),
  ('OL20129837W', 'The Testaments', 'Margaret Atwood', 'Science Fiction, Young adult fiction, Dystopian Fiction, Fiction, dystopian, Fiction, fantasy, general, Canadian fiction (fictional works by one author)'),
  ('OL548197W', 'Among the Imposters', 'Margaret Peterson Haddix', 'Science Fiction, Young adult fiction, Dystopian Fiction')
