import React from 'react';
import Button from '../Button';
import button from '../Button';

export default function UserNotes() {
  return (
    <div>
      <h3>User Notes</h3>
      <p>Sect. is for details generated by the user and user Actions</p>
      <Button>Send Book to Friend</Button>
      <br />
      <textarea
        name='userNotes'
        rows='15'
        cols='75'
        placeholder='Any notes about the book? Write them here...'
      ></textarea>
      <br />
      <Button>Save Notes</Button>
    </div>
  );
}
